---

- name: DOCKER | INSTALL REPO
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

- name: DOCKER | INSTALL
  yum: name=docker-engine

- name: DOCKER | START SERVICE
  service: name=docker state=started enabled=yes
